[package]
name = "bintool"
version = "0.1.0"
authors = ["Nathan Marley <nathan.marley@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
hex = "0.4"
nom = "7.1.3"
