[package]
name = "b64url"
version = "0.1.0"
authors = ["Nathan Marley <nathan.marley@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0"
hex = "0.4"
