[package]
name = "dq"
version = "0.1.0"
authors = ["Nathan Marley <nathan@glowberrylabs.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
tempfile = "3.6"
